trigger:
  branches:
    include:
      - master
  tags:
    include:
      - latest

jobs:
  - job: Release
    condition: eq(variables['Build.SourceBranch'], 'refs/tags/latest')
    pool:
      vmImage: ubuntu-16.04
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
    steps:
      - template: .azure-pipelines-steps.yml
      - bash: |
          echo "##vso[task.setvariable variable=PACKAGE_VERSION]$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')"
          echo "##vso[task.setvariable variable=CURRENT_GIT_TAG]$(git describe --tags | tr -d '[:space:]')"
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" >> .npmrc
      - script: npm dist-tag add aws-spot-price@$(PACKAGE_VERSION) $(CURRENT_GIT_TAG)
        displayName: "NPM dist-tag $(CURRENT_GIT_TAG)"
        env:
          NPM_TOKEN: $(NPM_TOKEN)

  - job: Linux
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/'), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
    pool:
      vmImage: ubuntu-16.04
    strategy:
      matrix:
        node_8_x:
          node_version: 8.x
        node_10_x:
          node_version: 10.x
        node_12_x:
          node_version: 12.x
    steps:
      - template: .azure-pipelines-steps.yml
      # sonar-scanner run only on node 10.x
      - bash: |
          echo "##vso[task.setvariable variable=PACKAGE_VERSION]$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')"
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: "sonarcloud"
          organization: "hoonoh"
          scannerMode: "CLI"
          configMode: "file"
        condition: eq(variables['node_version'], '10.x')
      - task: SonarCloudAnalyze@1
        condition: eq(variables['node_version'], '10.x')
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: "300"
        condition: eq(variables['node_version'], '10.x')
      # semantic-release run only on node 10.x & master branch (releases to next dist-tag)
      - script: yarn semantic-release || true
        displayName: Release
        condition: and(succeeded(), eq(variables['node_version'], '10.x'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          NPM_TOKEN: $(NPM_TOKEN)
          GH_TOKEN: $(GH_TOKEN)

  - job: Windows
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/'), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        node_8_x:
          node_version: 8.x
        node_10_x:
          node_version: 10.x
        node_12_x:
          node_version: 12.x
    steps:
      - script: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        displayName: "Preserve LF endings and symbolic links on check out"
      - template: .azure-pipelines-steps.yml

  - job: macOS
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/'), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
    pool:
      vmImage: macos-10.13
    strategy:
      matrix:
        node_8_x:
          node_version: 8.x
        node_10_x:
          node_version: 10.x
        node_12_x:
          node_version: 12.x
    steps:
      - template: .azure-pipelines-steps.yml

variables:
  CI: true
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
