version: '2'

exclude_patterns:
  - '.circleci/'
  - '.codeclimate.yml'
  - '.eslintrc.js'
  - '.gitignore'
  - '.npmignore'
  - '.prettierignore'
  - 'aws-spot-price.code-workspace'
  - 'bin/'
  - 'CHANGELOG.md'
  - 'commitlint.config.js'
  - 'docs/'
  - 'package.json'
  - 'patches/'
  - 'README.md'
  - 'scripts/'
  - 'src/**/*.spec.ts'
  - 'test/'
  - 'tsconfig.json'
  - '.yarn/'
  - 'yarn.lock'
  - sonar-project.properties
  - sonar-project.properties
  - webpack.config.js

checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
