ignorePatterns: ['husky/*']

env:
  es6: true
  node: true

settings:
  import/parsers:
    '@typescript-eslint/parser': [.ts]
  import/resolver:
    node:
      extensions: [.ts]

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.eslint.json

extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier

plugins:
  - unused-imports
  - '@typescript-eslint'
  - prettier
  - simple-import-sort

rules:
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  no-console: 0
  no-param-reassign: 0
  prettier/prettier: error
  simple-import-sort/imports: 2
  simple-import-sort/exports: 2

  # eslint-plugin-unused-imports
  '@typescript-eslint/no-unused-vars': off
  unused-imports/no-unused-imports-ts: error
  unused-imports/no-unused-vars-ts:
    - warn
    - vars: all
      varsIgnorePattern: ^_
      args: after-used
      argsIgnorePattern: ^_

overrides:
  - files:
      - test/*.js
      - webpack.config.js
    rules:
      '@typescript-eslint/explicit-function-return-type': 0
      '@typescript-eslint/no-var-requires': 0
  - files:
      - '**/*.spec.ts'
      - test/jest.setup.js
      - test/**/*.ts
    env:
      jest/globals: true
    plugins:
      - jest
  - files:
      - '**/*.spec.ts'
      - util/**/*.ts
      - test/**/*.ts
    rules:
      import/no-extraneous-dependencies: 0
      '@typescript-eslint/ban-ts-ignore': 0
      'no-underscore-dangle': 0
