on:
  push:
    branches: [master]

jobs:
  semantic-release:
    if: startsWith(github.event.head_commit.message, 'chore(release):')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.checkout_ref }}

      - name: update latest tag
        run: git tag -f latest && git push -d origin latest && git push origin master --tags
